"""
Professional Shipment PDF Generator
Freight CRM
"""

import os
from datetime import datetime
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Image,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.pdfgen import canvas


# ==========================================================
# TEMPORARY COMPANY INFORMATION
# ==========================================================

COMPANY_NAME = "ABC FREIGHT LOGISTICS"

COMPANY_ADDRESS = (
    "Hyderabad, Telangana, India"
)

COMPANY_PHONE = "+91 9876543210"

COMPANY_EMAIL = "info@abclogistics.com"

COMPANY_WEBSITE = "www.abclogistics.com"


# Change later to database/company settings
LOGO_PATH = os.path.join(
    "app",
    "static",
    "images",
    "company-logo.png",
)


# ==========================================================
# CRM COLORS
# ==========================================================

PRIMARY = colors.HexColor("#7f1d1d")
PRIMARY_LIGHT = colors.HexColor("#fef2f2")

GREEN = colors.HexColor("#16a34a")
GREEN_BG = colors.HexColor("#dcfce7")

ORANGE = colors.HexColor("#ea580c")
ORANGE_BG = colors.HexColor("#ffedd5")

BLUE = colors.HexColor("#2563eb")
BLUE_BG = colors.HexColor("#dbeafe")

GRAY = colors.HexColor("#6b7280")
LIGHT_GRAY = colors.HexColor("#f3f4f6")

BLACK = colors.HexColor("#111827")


# ==========================================================
# STYLES
# ==========================================================

styles = getSampleStyleSheet()

TITLE_STYLE = ParagraphStyle(
    "TITLE_STYLE",
    parent=styles["Heading1"],
    alignment=TA_CENTER,
    fontSize=22,
    textColor=PRIMARY,
    spaceAfter=8,
)

SECTION_STYLE = ParagraphStyle(
    "SECTION_STYLE",
    parent=styles["Heading2"],
    fontSize=13,
    textColor=PRIMARY,
    spaceBefore=16,
    spaceAfter=8,
)

LABEL_STYLE = ParagraphStyle(
    "LABEL_STYLE",
    parent=styles["BodyText"],
    fontSize=9,
    textColor=GRAY,
)

VALUE_STYLE = ParagraphStyle(
    "VALUE_STYLE",
    parent=styles["BodyText"],
    fontSize=10,
    textColor=BLACK,
)

FOOTER_STYLE = ParagraphStyle(
    "FOOTER_STYLE",
    parent=styles["BodyText"],
    alignment=TA_CENTER,
    fontSize=8,
    textColor=GRAY,
)


# ==========================================================
# LOGO
# ==========================================================

def get_company_logo(width=1.0 * inch):
    """
    Return company logo if available.
    """

    if os.path.exists(LOGO_PATH):
        logo = Image(LOGO_PATH)
        logo.drawWidth = width
        logo.drawHeight = width * 0.60
        return logo

    return Paragraph(
        "<b>LOGO</b>",
        VALUE_STYLE,
    )


# ==========================================================
# PAGE HEADER
# ==========================================================

def draw_header(story):
    """
    Company Header
    """

    logo = get_company_logo()

    info = Paragraph(
        f"""
        <font size="16"><b>{COMPANY_NAME}</b></font><br/>
        {COMPANY_ADDRESS}<br/>
        {COMPANY_PHONE}<br/>
        {COMPANY_EMAIL}<br/>
        {COMPANY_WEBSITE}
        """,
        VALUE_STYLE,
    )

    table = Table(
        [[logo, info]],
        colWidths=[1.4 * inch, 5.6 * inch],
    )

    table.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
            ]
        )
    )

    story.append(table)
    story.append(Spacer(1, 10))

    story.append(
        Paragraph(
            "SHIPMENT REPORT",
            TITLE_STYLE,
        )
    )

    story.append(Spacer(1, 12))


# ==========================================================
# PAGE FOOTER
# ==========================================================

def add_page_footer(canvas, doc):
    """
    Footer for every page.
    """

    canvas.saveState()

    canvas.setStrokeColor(PRIMARY)
    canvas.line(
        40,
        40,
        doc.pagesize[0] - 40,
        40,
    )

    canvas.setFont(
        "Helvetica",
        8,
    )

    canvas.drawString(
        40,
        25,
        "Generated by Freight CRM",
    )

    canvas.drawRightString(
        doc.pagesize[0] - 40,
        25,
        f"Page {canvas.getPageNumber()}",
    )

    canvas.restoreState()
    # ==========================================================
# SHIPMENT SUMMARY
# ==========================================================

def build_shipment_summary(story, shipment):
    """
    Shipment Summary Section
    """

    story.append(
        Paragraph(
            "Shipment Summary",
            SECTION_STYLE,
        )
    )

    status = (
        shipment.shipment_status
        .replace("_", " ")
        .title()
    )

    mode = (
        shipment.mode_of_shipment
        .replace("_", " ")
        .title()
    )

    etd = (
        shipment.etd.strftime("%d %b %Y")
        if shipment.etd
        else "-"
    )

    eta = (
        shipment.eta.strftime("%d %b %Y")
        if shipment.eta
        else "-"
    )

    generated = datetime.now().strftime("%d %b %Y %I:%M %p")

    data = [
        ["Shipment Ref", shipment.shipment_reference],
        ["Client", shipment.client.company_name],
        ["Status", status],
        ["Mode", mode],
        ["Origin", shipment.origin],
        ["Destination", shipment.destination],
        ["ETD", etd],
        ["ETA", eta],
        ["Generated On", generated],
    ]

    table = Table(
        data,
        colWidths=[1.7 * inch, 4.8 * inch],
    )

    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), PRIMARY_LIGHT),
                ("TEXTCOLOR", (0, 0), (0, -1), PRIMARY),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("FONTNAME", (1, 0), (1, -1), "Helvetica"),
                ("GRID", (0, 0), (-1, -1), 0.3, colors.grey),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
                ("TOPPADDING", (0, 0), (-1, -1), 7),
                ("BACKGROUND", (1, 0), (1, -1), colors.white),
            ]
        )
    )

    story.append(table)
    story.append(Spacer(1, 18))


# ==========================================================
# CLIENT INFORMATION
# ==========================================================

def build_client_information(story, shipment):
    """
    Client Information Section
    """

    story.append(
        Paragraph(
            "Client Information",
            SECTION_STYLE,
        )
    )

    client = shipment.client

    contact = getattr(client, "contact_person", "") or "-"
    email = getattr(client, "email", "") or "-"
    phone = getattr(client, "phone", "") or "-"
    country = getattr(client, "country", "") or "-"
    city = getattr(client, "city", "") or "-"

    data = [
        ["Company", client.company_name],
        ["Contact Person", contact],
        ["Email", email],
        ["Phone", phone],
        ["City", city],
        ["Country", country],
    ]

    table = Table(
        data,
        colWidths=[1.8 * inch, 4.7 * inch],
    )

    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), BLUE_BG),
                ("TEXTCOLOR", (0, 0), (0, -1), BLUE),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.3, colors.grey),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
                ("TOPPADDING", (0, 0), (-1, -1), 7),
            ]
        )
    )

    story.append(table)
    story.append(Spacer(1, 18))


# ==========================================================
# SHIPMENT DETAILS
# ==========================================================

def build_shipment_details(story, shipment):
    """
    Shipment Details Section
    """

    story.append(
        Paragraph(
            "Shipment Details",
            SECTION_STYLE,
        )
    )

    handled_by = (
        shipment.handled_by.full_name
        if shipment.handled_by
        else "-"
    )

    created_by = (
        shipment.created_by.full_name
        if shipment.created_by
        else "-"
    )

    created = (
        shipment.created_at.strftime("%d %b %Y")
        if shipment.created_at
        else "-"
    )

    cargo = shipment.cargo_description or "-"
    weight = shipment.cargo_weight_volume or "-"

    data = [
        ["Cargo Description", cargo],
        ["Weight / Volume", weight],
        ["Handled By", handled_by],
        ["Created By", created_by],
        ["Created On", created],
    ]

    table = Table(
        data,
        colWidths=[2.0 * inch, 4.5 * inch],
    )

    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), LIGHT_GRAY),
                ("TEXTCOLOR", (0, 0), (0, -1), BLACK),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.3, colors.grey),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
                ("TOPPADDING", (0, 0), (-1, -1), 7),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]
        )
    )

    story.append(table)
    story.append(Spacer(1, 18))
    # ==========================================================
# OPERATIONAL WORKFLOW
# ==========================================================

def build_workflow_section(story, shipment, milestones):
    """
    Shipment Operational Workflow
    """

    story.append(
        Paragraph(
            "Operational Workflow",
            SECTION_STYLE,
        )
    )

    workflow = [
        "booked",
        "cargo_picked_up",
        "in_transit",
        "arrived_destination",
        "customs_clearance",
        "out_for_delivery",
        "delivered",
        "closed_completed",
    ]

    labels = {
        "booked": "Booked",
        "cargo_picked_up": "Cargo Picked Up",
        "in_transit": "In Transit",
        "arrived_destination": "Arrived Destination",
        "customs_clearance": "Customs Clearance",
        "out_for_delivery": "Out For Delivery",
        "delivered": "Delivered",
        "closed_completed": "Closed",
    }

    completed = {}

    for m in milestones:
        completed[m.stage] = m

    rows = [["Stage", "Status", "Completed By", "Completed On"]]

    for stage in workflow:

        if stage in completed:

            m = completed[stage]

            rows.append([
                labels[stage],
                "Completed",
                m.completed_by.full_name if m.completed_by else "-",
                m.completed_at.strftime("%d %b %Y %H:%M")
                if m.completed_at else "-"
            ])

        else:

            rows.append([
                labels[stage],
                "Pending",
                "-",
                "-"
            ])

    table = Table(
        rows,
        colWidths=[
            2.4 * inch,
            1.2 * inch,
            1.5 * inch,
            1.5 * inch,
        ],
    )

    style = TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), PRIMARY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), .30, colors.grey),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ("TOPPADDING", (0, 0), (-1, -1), 7),
    ])

    for r in range(1, len(rows)):

        if rows[r][1] == "Completed":
            style.add(
                "BACKGROUND",
                (1, r),
                (1, r),
                GREEN_BG,
            )
            style.add(
                "TEXTCOLOR",
                (1, r),
                (1, r),
                GREEN,
            )

        else:
            style.add(
                "BACKGROUND",
                (1, r),
                (1, r),
                ORANGE_BG,
            )
            style.add(
                "TEXTCOLOR",
                (1, r),
                (1, r),
                ORANGE,
            )

    table.setStyle(style)

    story.append(table)
    story.append(Spacer(1, 18))


# ==========================================================
# DOCUMENT STATUS
# ==========================================================

def build_document_section(story, documents):
    """
    Shipment Documents
    """
    if not documents:

        story.append(
        Paragraph(
            "No shipment documents available.",
            VALUE_STYLE,
        )
    )

    story.append(Spacer(1, 18))
    return
    story.append(
        Paragraph(
            "Shipment Documents",
            SECTION_STYLE,
        )
    )

    rows = [[
        "Document",
        "Type",
        "Status",
        "Remarks",
    ]]

    for d in documents:

        rows.append([
            d.document_name,
            d.document_type.replace("_", " ").title(),
            d.status.replace("_", " ").title(),
            d.remarks or "-"
        ])

    table = Table(
        rows,
        colWidths=[
            2.2 * inch,
            1.4 * inch,
            1.2 * inch,
            2.2 * inch,
        ],
    )

    style = TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), BLUE),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), .30, colors.grey),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ("TOPPADDING", (0, 0), (-1, -1), 7),
    ])

    for r in range(1, len(rows)):

        status = rows[r][2].lower()

        if status == "received":

            style.add(
                "BACKGROUND",
                (2, r),
                (2, r),
                GREEN_BG,
            )

        elif status == "pending":

            style.add(
                "BACKGROUND",
                (2, r),
                (2, r),
                ORANGE_BG,
            )

        else:

            style.add(
                "BACKGROUND",
                (2, r),
                (2, r),
                LIGHT_GRAY,
            )

    table.setStyle(style)

    story.append(table)
    story.append(Spacer(1, 18))


# ==========================================================
# CUSTOMS CLEARANCE
# ==========================================================

def build_customs_section(story, customs):
    """
    Customs Clearance
    """

    story.append(
        Paragraph(
            "Customs Clearance",
            SECTION_STYLE,
        )
    )

    if not customs:

        story.append(
            Paragraph(
                "No customs clearance information available.",
                VALUE_STYLE,
            )
        )

        story.append(Spacer(1, 18))
        return

    rows = [

        [
            "Clearance Required",
            "Yes" if customs.clearance_required else "No"
        ],

        [
            "Status",
            customs.clearance_status.replace("_", " ").title()
        ],

        [
            "Clearing Agent",
            customs.clearing_agent_name or "-"
        ],

        [
            "Clearance Date",
            customs.clearance_date.strftime("%d %b %Y")
            if customs.clearance_date else "-"
        ],

        [
            "Remarks",
            customs.remarks or "-"
        ],
    ]

    table = Table(
        rows,
        colWidths=[
            2.0 * inch,
            4.5 * inch,
        ],
    )

    table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), BLUE_BG),
            ("TEXTCOLOR", (0, 0), (0, -1), BLUE),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), .30, colors.grey),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
            ("TOPPADDING", (0, 0), (-1, -1), 7),
        ])
    )

    story.append(table)
    story.append(Spacer(1, 18))
    # ==========================================================
# SHIPMENT CLOSURE
# ==========================================================

def build_closure_section(story, closure):
    """
    Shipment Closure Details
    """

    story.append(
        Paragraph(
            "Shipment Closure",
            SECTION_STYLE,
        )
    )

    if not closure:

        story.append(
            Paragraph(
                "Shipment has not been closed yet.",
                VALUE_STYLE,
            )
        )

        story.append(Spacer(1, 18))
        return

    closing_date = (
        closure.closing_date.strftime("%d %b %Y")
        if getattr(closure, "closing_date", None)
        else "-"
    )

    closed_by = "-"

    if getattr(closure, "closed_by", None):
        closed_by = (
            getattr(
                closure.closed_by,
                "full_name",
                "-"
            )
        )

    rating = getattr(
        closure,
        "client_rating",
        None
    )

    rating = (
        f"{rating} / 5"
        if rating
        else "-"
    )

    archive = (
        "Yes"
        if getattr(
            closure,
            "document_archive_confirmed",
            False
        )
        else "No"
    )

    data = [

        [
            "Closing Status",
            (
                getattr(
                    closure,
                    "closing_status",
                    "-"
                )
                .replace("_", " ")
                .title()
            )
        ],

        [
            "Closing Date",
            closing_date
        ],

        [
            "Closed By",
            closed_by
        ],

        [
            "Documents Archived",
            archive
        ],

        [
            "Client Rating",
            rating
        ],

        [
            "Client Feedback",
            getattr(
                closure,
                "client_feedback",
                "-"
            ) or "-"
        ],

        [
            "Closing Notes",
            getattr(
                closure,
                "closing_notes",
                "-"
            ) or "-"
        ],

    ]

    table = Table(
        data,
        colWidths=[
            2.0 * inch,
            4.5 * inch,
        ],
    )

    table.setStyle(
        TableStyle(
            [

                (
                    "BACKGROUND",
                    (0, 0),
                    (0, -1),
                    GREEN_BG,
                ),

                (
                    "TEXTCOLOR",
                    (0, 0),
                    (0, -1),
                    GREEN,
                ),

                (
                    "FONTNAME",
                    (0, 0),
                    (0, -1),
                    "Helvetica-Bold",
                ),

                (
                    "GRID",
                    (0, 0),
                    (-1, -1),
                    .30,
                    colors.grey,
                ),

                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    7,
                ),

                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    7,
                ),

                (
                    "VALIGN",
                    (0, 0),
                    (-1, -1),
                    "TOP",
                ),

            ]
        )
    )

    story.append(table)
    story.append(Spacer(1, 20))


# ==========================================================
# WATERMARK
# ==========================================================

def draw_watermark(canvas, doc):
    """
    Draw Confidential watermark
    """

    canvas.saveState()

    canvas.setFont(
        "Helvetica-Bold",
        60,
    )

    canvas.setFillColor(
        colors.Color(
            .92,
            .92,
            .92,
            alpha=.25,
        )
    )

    canvas.translate(
        doc.pagesize[0] / 2,
        doc.pagesize[1] / 2,
    )

    canvas.rotate(45)

    canvas.drawCentredString(
        0,
        0,
        "CONFIDENTIAL",
    )

    canvas.restoreState()


# ==========================================================
# PAGE CALLBACK
# ==========================================================

def add_page_elements(canvas, doc):
    """
    Footer + Watermark
    """

    draw_watermark(
        canvas,
        doc,
    )

    add_page_footer(
        canvas,
        doc,
    )
    from reportlab.platypus import SimpleDocTemplate


# ==========================================================
# GENERATE SHIPMENT PDF
# ==========================================================

def generate_shipment_pdf(
    shipment,
    milestones,
    documents,
    customs,
    closure,
):
    """
    Generate Professional Shipment PDF
    """

    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        rightMargin=30,
        leftMargin=30,
        topMargin=35,
        bottomMargin=45,
    )

    story = []

    # ----------------------------------------
    # Header
    # ----------------------------------------

    draw_header(story)

    # ----------------------------------------
    # Shipment Summary
    # ----------------------------------------

    build_shipment_summary(
        story,
        shipment,
    )

    # ----------------------------------------
    # Client
    # ----------------------------------------

    build_client_information(
        story,
        shipment,
    )

    # ----------------------------------------
    # Shipment Details
    # ----------------------------------------

    build_shipment_details(
        story,
        shipment,
    )

    # ----------------------------------------
    # Workflow
    # ----------------------------------------

    build_workflow_section(
        story,
        shipment,
        milestones,
    )

    # ----------------------------------------
    # Documents
    # ----------------------------------------

    build_document_section(
        story,
        documents,
    )

    # ----------------------------------------
    # Customs
    # ----------------------------------------

    build_customs_section(
        story,
        customs,
    )

    # ----------------------------------------
    # Closure
    # ----------------------------------------

    build_closure_section(
        story,
        closure,
    )

    # ----------------------------------------
    # Footer
    # ----------------------------------------

    doc.build(
        story,
        onFirstPage=add_page_elements,
        onLaterPages=add_page_elements,
    )

    buffer.seek(0)

    return buffer