"""Add origin_port and destination_port to quotations

Revision ID: 00916bb9a27c
Revises: f4319157e2e9
Create Date: 2026-07-21 20:19:33.677667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00916bb9a27c'
down_revision = 'f4319157e2e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin_port', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('destination_port', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_column('destination_port')
        batch_op.drop_column('origin_port')

    # ### end Alembic commands ###
