"""add quotation soft delete

Revision ID: 03eeccb47caf
Revises: 61311da1fc03
Create Date: 2026-07-21 15:31:24.401135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03eeccb47caf'
down_revision = '61311da1fc03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
        with op.batch_alter_table('quotations', schema=None) as batch_op:
            batch_op.add_column(
            sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text("0"))
        )
        batch_op.drop_column('cost_breakdown')
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
        with op.batch_alter_table('quotations', schema=None) as batch_op:
            batch_op.add_column(sa.Column('cost_breakdown', sa.TEXT(), nullable=True))
            batch_op.drop_column('is_deleted')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
