"""change numeric to float

Revision ID: 058c17aa07bb
Revises: 536469bcd7b9
Create Date: 2026-07-20 03:00:14.996327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '058c17aa07bb'
down_revision = '536469bcd7b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enquiries', schema=None) as batch_op:
        batch_op.alter_column('weight_kg',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('volume_cbm',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enquiries', schema=None) as batch_op:
        batch_op.alter_column('volume_cbm',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('weight_kg',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###
