"""Add other_client_name to quotations

Revision ID: 1554994605f2
Revises: cfbe39293d15
Create Date: 2026-07-21 13:37:34.420883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1554994605f2'
down_revision = 'cfbe39293d15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_pipeline_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_client_name', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_pipeline_history', schema=None) as batch_op:
        batch_op.drop_column('other_client_name')

    # ### end Alembic commands ###
