"""Add client portal users

Revision ID: 29943298c0d6
Revises: 
Create Date: 2026-07-11 12:24:15.848217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29943298c0d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_client_reference'), ['client_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_clients_pipeline_stage'), ['pipeline_stage'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_pipeline_stage'))
        batch_op.drop_index(batch_op.f('ix_clients_client_reference'))

    # ### end Alembic commands ###
