"""add quotation cost fields

Revision ID: 536469bcd7b9
Revises: 6771a5216754
Create Date: 2026-07-20 02:52:45.623283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '536469bcd7b9'
down_revision = '6771a5216754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_column('cost_breakdown')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_breakdown', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
