"""add quotation shipment fields

Revision ID: 61311da1fc03
Revises: cf667b93aa55
Create Date: 2026-07-21 15:08:43.801427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61311da1fc03'
down_revision = 'cf667b93aa55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('destination', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('mode_of_shipment', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cargo_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cargo_weight_volume', sa.String(length=100), nullable=True))
        batch_op.drop_column('cost_breakdown')

    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipments_client_id'))
        batch_op.drop_index(batch_op.f('ix_shipments_enquiry_id'))
        
       

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        
       
        batch_op.create_index(batch_op.f('ix_shipments_enquiry_id'), ['enquiry_id'], unique=1)
        batch_op.create_index(batch_op.f('ix_shipments_client_id'), ['client_id'], unique=False)

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_breakdown', sa.TEXT(), nullable=True))
        batch_op.drop_column('cargo_weight_volume')
        batch_op.drop_column('cargo_description')
        batch_op.drop_column('mode_of_shipment')
        batch_op.drop_column('destination')
        batch_op.drop_column('origin')

    # ### end Alembic commands ###
