"""Added payment_terms to Quotation model

Revision ID: 6dfcbf280bf1
Revises: ab753bd554b5
Create Date: 2026-07-19 13:34:50.469120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dfcbf280bf1'
down_revision = 'ab753bd554b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.alter_column('payment_terms',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_column('cost_breakdown')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_breakdown', sa.TEXT(), nullable=True))
        batch_op.alter_column('payment_terms',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
