"""add quotation cost fields

Revision ID: 7af071d3b2a1
Revises: 058c17aa07bb
Create Date: 2026-07-20 03:05:24.912555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7af071d3b2a1'
down_revision = '058c17aa07bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_column('cost_breakdown')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_breakdown', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
