"""Fresh start with all fields

Revision ID: ab753bd554b5
Revises: 
Create Date: 2026-07-19 13:26:28.933648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab753bd554b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('file_id', sa.String(length=255), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_reference', sa.String(length=50), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('pipeline_stage', sa.String(length=50), nullable=True),
    sa.Column('contact_person_name', sa.String(length=150), nullable=False),
    sa.Column('designation', sa.String(length=150), nullable=True),
    sa.Column('primary_phone', sa.String(length=50), nullable=False),
    sa.Column('secondary_phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('website_url', sa.String(length=300), nullable=True),
    sa.Column('address_line_1', sa.String(length=300), nullable=False),
    sa.Column('address_line_2', sa.String(length=300), nullable=True),
    sa.Column('industry_sector', sa.String(length=150), nullable=True),
    sa.Column('services_needed', sa.JSON(), nullable=False),
    sa.Column('secondary_contact_details', sa.JSON(), nullable=True),
    sa.Column('company_registration_number', sa.String(length=100), nullable=True),
    sa.Column('tax_vat_number', sa.String(length=100), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('payment_terms', sa.String(length=100), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=False),
    sa.Column('lead_source', sa.String(length=100), nullable=True),
    sa.Column('date_added', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_contact_date', sa.Date(), nullable=True),
    sa.Column('next_follow_up_date', sa.Date(), nullable=True),
    sa.Column('priority_level', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_assigned_to_id'), ['assigned_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_client_reference'), ['client_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_clients_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_date_added'), ['date_added'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_is_archived'), ['is_archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_next_follow_up_date'), ['next_follow_up_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_pipeline_stage'), ['pipeline_stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_primary_phone'), ['primary_phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_priority_level'), ['priority_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_status'), ['status'], unique=False)

    op.create_table('client_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('activity_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_activities_activity_date'), ['activity_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_activities_activity_type'), ['activity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_activities_client_id'), ['client_id'], unique=False)

    op.create_table('client_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    with op.batch_alter_table('client_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_attachments_client_id'), ['client_id'], unique=False)

    op.create_table('client_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('performed_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_audit_logs_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_audit_logs_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_audit_logs_performed_by_id'), ['performed_by_id'], unique=False)

    op.create_table('client_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_notes_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_notes_created_at'), ['created_at'], unique=False)

    op.create_table('client_pipeline_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('old_stage', sa.String(length=50), nullable=True),
    sa.Column('new_stage', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('moved_by_id', sa.Integer(), nullable=False),
    sa.Column('moved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['moved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_pipeline_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_pipeline_history_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_pipeline_history_moved_at'), ['moved_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_pipeline_history_moved_by_id'), ['moved_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_pipeline_history_new_stage'), ['new_stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_pipeline_history_old_stage'), ['old_stage'], unique=False)

    op.create_table('client_portal_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('client_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_status_history_changed_at'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_status_history_client_id'), ['client_id'], unique=False)

    op.create_table('client_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_tasks_assigned_to_id'), ['assigned_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_tasks_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_tasks_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_tasks_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_tasks_task_type'), ['task_type'], unique=False)

    op.create_table('enquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enquiry_reference', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('enquiry_date', sa.Date(), nullable=False),
    sa.Column('expected_timeline', sa.String(length=150), nullable=True),
    sa.Column('incoterms', sa.String(length=50), nullable=True),
    sa.Column('additional_instructions', sa.Text(), nullable=True),
    sa.Column('origin', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('mode_of_shipment', sa.String(length=50), nullable=False),
    sa.Column('equipment_type', sa.String(length=50), nullable=True),
    sa.Column('cargo_description', sa.Text(), nullable=False),
    sa.Column('total_pieces', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('volume_cbm', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cargo_weight_volume', sa.String(length=150), nullable=True),
    sa.Column('handled_by_id', sa.Integer(), nullable=False),
    sa.Column('sales_coordinator_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['handled_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sales_coordinator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enquiries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enquiries_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enquiries_enquiry_date'), ['enquiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_enquiries_enquiry_reference'), ['enquiry_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_enquiries_handled_by_id'), ['handled_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enquiries_mode_of_shipment'), ['mode_of_shipment'], unique=False)
        batch_op.create_index(batch_op.f('ix_enquiries_sales_coordinator_id'), ['sales_coordinator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enquiries_status'), ['status'], unique=False)

    op.create_table('support_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('admin_reply', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_tickets_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_status'), ['status'], unique=False)

    op.create_table('quotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_number', sa.String(length=50), nullable=False),
    sa.Column('enquiry_id', sa.Integer(), nullable=False),
    sa.Column('quotation_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('validity_date', sa.Date(), nullable=False),
    sa.Column('document_original_filename', sa.String(length=255), nullable=True),
    sa.Column('document_stored_filename', sa.String(length=255), nullable=True),
    sa.Column('document_file_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('shipping_line_airline', sa.String(length=150), nullable=True),
    sa.Column('no_of_containers', sa.Integer(), nullable=True),
    sa.Column('container_type_quota', sa.String(length=50), nullable=True),
    sa.Column('etd', sa.DateTime(), nullable=True),
    sa.Column('cutoff_date_documentation', sa.DateTime(), nullable=True),
    sa.Column('cutoff_date_cargo', sa.DateTime(), nullable=True),
    sa.Column('free_time_days', sa.Integer(), nullable=True),
    sa.Column('transit_time_days', sa.Integer(), nullable=True),
    sa.Column('incoterms', sa.String(length=50), nullable=True),
    sa.Column('hs_code', sa.String(length=50), nullable=True),
    sa.Column('ocean_air_freight', sa.Float(), nullable=True),
    sa.Column('origin_charges', sa.Float(), nullable=True),
    sa.Column('destination_charges', sa.Float(), nullable=True),
    sa.Column('insurance_charges', sa.Float(), nullable=True),
    sa.Column('other_surcharges', sa.Float(), nullable=True),
    sa.Column('remarks_terms', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotations_currency'), ['currency'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotations_enquiry_id'), ['enquiry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotations_quotation_number'), ['quotation_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_quotations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotations_validity_date'), ['validity_date'], unique=False)

    op.create_table('support_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_messages_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('shipment_party_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('enquiry_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=255), nullable=False),
    sa.Column('agent_country', sa.String(length=120), nullable=False),
    sa.Column('agent_contact_person', sa.String(length=255), nullable=False),
    sa.Column('agent_phone', sa.String(length=50), nullable=False),
    sa.Column('agent_email', sa.String(length=255), nullable=False),
    sa.Column('agent_reference', sa.String(length=255), nullable=True),
    sa.Column('shipper_name', sa.String(length=255), nullable=False),
    sa.Column('shipper_address', sa.Text(), nullable=False),
    sa.Column('shipper_contact_person', sa.String(length=255), nullable=False),
    sa.Column('shipper_phone', sa.String(length=50), nullable=False),
    sa.Column('consignee_name', sa.String(length=255), nullable=False),
    sa.Column('consignee_address', sa.Text(), nullable=False),
    sa.Column('consignee_contact_person', sa.String(length=255), nullable=False),
    sa.Column('consignee_phone', sa.String(length=50), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipment_party_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipment_party_details_enquiry_id'), ['enquiry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_party_details_quotation_id'), ['quotation_id'], unique=True)

    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_reference', sa.String(length=50), nullable=False),
    sa.Column('enquiry_id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('mode_of_shipment', sa.String(length=50), nullable=False),
    sa.Column('cargo_description', sa.Text(), nullable=False),
    sa.Column('cargo_weight_volume', sa.String(length=150), nullable=True),
    sa.Column('shipment_status', sa.String(length=30), nullable=False),
    sa.Column('current_stage', sa.String(length=50), nullable=False),
    sa.Column('handled_by_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hbl_no', sa.String(length=100), nullable=True),
    sa.Column('shipper_name', sa.String(length=255), nullable=True),
    sa.Column('consignee_address', sa.Text(), nullable=True),
    sa.Column('container_no', sa.String(length=50), nullable=True),
    sa.Column('container_type', sa.String(length=20), nullable=True),
    sa.Column('shipping_line', sa.String(length=100), nullable=True),
    sa.Column('vessel', sa.String(length=100), nullable=True),
    sa.Column('cargo_details', sa.String(length=255), nullable=True),
    sa.Column('volume', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('etd', sa.DateTime(), nullable=True),
    sa.Column('eta', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['handled_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hbl_no')
    )
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipments_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_current_stage'), ['current_stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_enquiry_id'), ['enquiry_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_shipments_handled_by_id'), ['handled_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_mode_of_shipment'), ['mode_of_shipment'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_quotation_id'), ['quotation_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_shipments_shipment_reference'), ['shipment_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_shipments_shipment_status'), ['shipment_status'], unique=False)

    op.create_table('shipment_closures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('closing_status', sa.String(length=30), nullable=False),
    sa.Column('closing_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closing_notes', sa.Text(), nullable=True),
    sa.Column('document_archive_confirmed', sa.Boolean(), nullable=False),
    sa.Column('client_feedback', sa.Text(), nullable=True),
    sa.Column('client_rating', sa.Integer(), nullable=True),
    sa.Column('closed_by_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipment_closures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipment_closures_closing_date'), ['closing_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_closures_closing_status'), ['closing_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_closures_document_archive_confirmed'), ['document_archive_confirmed'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_closures_shipment_id'), ['shipment_id'], unique=True)

    op.create_table('shipment_customs_clearances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('clearance_required', sa.Boolean(), nullable=False),
    sa.Column('clearance_status', sa.String(length=30), nullable=False),
    sa.Column('clearing_agent_name', sa.String(length=255), nullable=True),
    sa.Column('clearance_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipment_customs_clearances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipment_customs_clearances_clearance_date'), ['clearance_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_customs_clearances_clearance_required'), ['clearance_required'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_customs_clearances_clearance_status'), ['clearance_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_customs_clearances_shipment_id'), ['shipment_id'], unique=True)

    op.create_table('shipment_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('document_name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_id', 'document_type', name='uq_shipment_document_type')
    )
    with op.batch_alter_table('shipment_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipment_documents_document_type'), ['document_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_documents_shipment_id'), ['shipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_documents_status'), ['status'], unique=False)

    op.create_table('shipment_milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_id', 'stage', name='uq_shipment_stage')
    )
    with op.batch_alter_table('shipment_milestones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipment_milestones_shipment_id'), ['shipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_milestones_stage'), ['stage'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_milestones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipment_milestones_stage'))
        batch_op.drop_index(batch_op.f('ix_shipment_milestones_shipment_id'))

    op.drop_table('shipment_milestones')
    with op.batch_alter_table('shipment_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipment_documents_status'))
        batch_op.drop_index(batch_op.f('ix_shipment_documents_shipment_id'))
        batch_op.drop_index(batch_op.f('ix_shipment_documents_document_type'))

    op.drop_table('shipment_documents')
    with op.batch_alter_table('shipment_customs_clearances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipment_customs_clearances_shipment_id'))
        batch_op.drop_index(batch_op.f('ix_shipment_customs_clearances_clearance_status'))
        batch_op.drop_index(batch_op.f('ix_shipment_customs_clearances_clearance_required'))
        batch_op.drop_index(batch_op.f('ix_shipment_customs_clearances_clearance_date'))

    op.drop_table('shipment_customs_clearances')
    with op.batch_alter_table('shipment_closures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipment_closures_shipment_id'))
        batch_op.drop_index(batch_op.f('ix_shipment_closures_document_archive_confirmed'))
        batch_op.drop_index(batch_op.f('ix_shipment_closures_closing_status'))
        batch_op.drop_index(batch_op.f('ix_shipment_closures_closing_date'))

    op.drop_table('shipment_closures')
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipments_shipment_status'))
        batch_op.drop_index(batch_op.f('ix_shipments_shipment_reference'))
        batch_op.drop_index(batch_op.f('ix_shipments_quotation_id'))
        batch_op.drop_index(batch_op.f('ix_shipments_mode_of_shipment'))
        batch_op.drop_index(batch_op.f('ix_shipments_handled_by_id'))
        batch_op.drop_index(batch_op.f('ix_shipments_enquiry_id'))
        batch_op.drop_index(batch_op.f('ix_shipments_current_stage'))
        batch_op.drop_index(batch_op.f('ix_shipments_client_id'))

    op.drop_table('shipments')
    with op.batch_alter_table('shipment_party_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipment_party_details_quotation_id'))
        batch_op.drop_index(batch_op.f('ix_shipment_party_details_enquiry_id'))

    op.drop_table('shipment_party_details')
    with op.batch_alter_table('support_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_messages_ticket_id'))

    op.drop_table('support_messages')
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotations_validity_date'))
        batch_op.drop_index(batch_op.f('ix_quotations_status'))
        batch_op.drop_index(batch_op.f('ix_quotations_quotation_number'))
        batch_op.drop_index(batch_op.f('ix_quotations_enquiry_id'))
        batch_op.drop_index(batch_op.f('ix_quotations_currency'))

    op.drop_table('quotations')
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_tickets_status'))
        batch_op.drop_index(batch_op.f('ix_support_tickets_client_id'))

    op.drop_table('support_tickets')
    with op.batch_alter_table('enquiries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enquiries_status'))
        batch_op.drop_index(batch_op.f('ix_enquiries_sales_coordinator_id'))
        batch_op.drop_index(batch_op.f('ix_enquiries_mode_of_shipment'))
        batch_op.drop_index(batch_op.f('ix_enquiries_handled_by_id'))
        batch_op.drop_index(batch_op.f('ix_enquiries_enquiry_reference'))
        batch_op.drop_index(batch_op.f('ix_enquiries_enquiry_date'))
        batch_op.drop_index(batch_op.f('ix_enquiries_client_id'))

    op.drop_table('enquiries')
    with op.batch_alter_table('client_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_tasks_task_type'))
        batch_op.drop_index(batch_op.f('ix_client_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_client_tasks_priority'))
        batch_op.drop_index(batch_op.f('ix_client_tasks_due_date'))
        batch_op.drop_index(batch_op.f('ix_client_tasks_client_id'))
        batch_op.drop_index(batch_op.f('ix_client_tasks_assigned_to_id'))

    op.drop_table('client_tasks')
    with op.batch_alter_table('client_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_status_history_client_id'))
        batch_op.drop_index(batch_op.f('ix_client_status_history_changed_at'))

    op.drop_table('client_status_history')
    op.drop_table('client_portal_users')
    with op.batch_alter_table('client_pipeline_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_pipeline_history_old_stage'))
        batch_op.drop_index(batch_op.f('ix_client_pipeline_history_new_stage'))
        batch_op.drop_index(batch_op.f('ix_client_pipeline_history_moved_by_id'))
        batch_op.drop_index(batch_op.f('ix_client_pipeline_history_moved_at'))
        batch_op.drop_index(batch_op.f('ix_client_pipeline_history_client_id'))

    op.drop_table('client_pipeline_history')
    with op.batch_alter_table('client_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_notes_created_at'))
        batch_op.drop_index(batch_op.f('ix_client_notes_client_id'))

    op.drop_table('client_notes')
    with op.batch_alter_table('client_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_audit_logs_performed_by_id'))
        batch_op.drop_index(batch_op.f('ix_client_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_client_audit_logs_client_id'))
        batch_op.drop_index(batch_op.f('ix_client_audit_logs_action_type'))
        batch_op.drop_index(batch_op.f('ix_client_audit_logs_action'))

    op.drop_table('client_audit_logs')
    with op.batch_alter_table('client_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_attachments_client_id'))

    op.drop_table('client_attachments')
    with op.batch_alter_table('client_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_activities_client_id'))
        batch_op.drop_index(batch_op.f('ix_client_activities_activity_type'))
        batch_op.drop_index(batch_op.f('ix_client_activities_activity_date'))

    op.drop_table('client_activities')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_status'))
        batch_op.drop_index(batch_op.f('ix_clients_priority_level'))
        batch_op.drop_index(batch_op.f('ix_clients_primary_phone'))
        batch_op.drop_index(batch_op.f('ix_clients_pipeline_stage'))
        batch_op.drop_index(batch_op.f('ix_clients_next_follow_up_date'))
        batch_op.drop_index(batch_op.f('ix_clients_is_archived'))
        batch_op.drop_index(batch_op.f('ix_clients_email'))
        batch_op.drop_index(batch_op.f('ix_clients_date_added'))
        batch_op.drop_index(batch_op.f('ix_clients_company_name'))
        batch_op.drop_index(batch_op.f('ix_clients_client_reference'))
        batch_op.drop_index(batch_op.f('ix_clients_category'))
        batch_op.drop_index(batch_op.f('ix_clients_assigned_to_id'))

    op.drop_table('clients')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('backup_logs')
    # ### end Alembic commands ###
