"""Make enquiry optional for quotations

Revision ID: b30a9f26d2d6
Revises: 7af071d3b2a1
Create Date: 2026-07-20 12:34:55.672985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b30a9f26d2d6'
down_revision = '7af071d3b2a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.alter_column('enquiry_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('cost_breakdown')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_breakdown', sa.TEXT(), nullable=True))
        batch_op.alter_column('enquiry_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
