"""Add other_client_name to quotations

Revision ID: c7c9a9a8ee91
Revises: 1554994605f2
Create Date: 2026-07-21 13:56:37.802145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c9a9a8ee91'
down_revision = '1554994605f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_client_name', sa.String(length=200), nullable=True))
        batch_op.drop_column('cost_breakdown')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_breakdown', sa.TEXT(), nullable=True))
        batch_op.drop_column('other_client_name')

    # ### end Alembic commands ###
