"""Support direct quotation shipments

Revision ID: cf667b93aa55
Revises: c7c9a9a8ee91
Create Date: 2026-07-21 14:27:01.690475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf667b93aa55'
down_revision = 'c7c9a9a8ee91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('shipment_party_details', schema=None) as batch_op:
        batch_op.alter_column('enquiry_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_client_name', sa.String(length=200), nullable=True))
        batch_op.alter_column('enquiry_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('enquiry_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('other_client_name')

    with op.batch_alter_table('shipment_party_details', schema=None) as batch_op:
        batch_op.alter_column('enquiry_id',
               existing_type=sa.INTEGER(),
               nullable=False)


    # ### end Alembic commands ###
