"""Added admin reply to support tickets

Revision ID: e3dd43af21d0
Revises: 
Create Date: 2026-07-12 16:20:45.911721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3dd43af21d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('admin_reply', sa.Text(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.drop_column('admin_reply')

    # ### end Alembic commands ###