"""Added enquiry ports

Revision ID: f4319157e2e9
Revises: 7cd9ae2d6e63
Create Date: 2026-07-21 18:30:10.028887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4319157e2e9'
down_revision = '7cd9ae2d6e63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enquiries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin_port', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('destination_port', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enquiries', schema=None) as batch_op:
        batch_op.drop_column('destination_port')
        batch_op.drop_column('origin_port')

    # ### end Alembic commands ###
